### PR TITLE
Stage 3 - Favourites Feature

### LINKED ISSUE #10: Favorites feature
Depends on #9

TODO:
- [x] User should have `favorites` list where you can save dog ids
- [x] On the dog detail screen, there should be a clickable ❤️ icon
- [x] When not active ❤️ is clicked, the dog should be added to favourites, and the Heart icon should be filled in red.
- [x] When active ❤️ is clicked, the dog should be removed to favourites, and only the heart outline should be visible
- [x] heart transition from active to inactive should be animated
- [x] While the heart is pressed, the icon should be smaller

### PR DESCRIPTION
**Pull request by filipo203**
A favourites feature has been included into the app. The user can mark dog images as 'favourite' with the heart icon in the top right corner of DogPreviewScreen. The heart icon is animated so that if a dog is favourited, heart is filled red, otherwise it's a black outline. Heart becomes smaller while pressed. Favourited dogs are displayed as a LazyList in the user profile page.

Key changes:
- Dog images displayed through dog image objects' image url from database instead of list of string with image urls to allow for favourite status to change.

Issues to fix:
- Dog images in favourites list are clickable and navigate to preview screen. However, dog images don't appear in preview screen when navigated through the profile screen.

### CODE REVIEW

**Comment by filipo203** [comment]
Possible fix?: 
Preview page currently recognises index of image from DogPicturesList which helps it display image. Maybe if unique dog ID from database was used instead that might fix the issue?

**Comment by filipo203** [comment]
~Dog images in favourites list are clickable and navigate to preview screen. However, dog images don't appear in preview screen when navigated through the profile screen.~
Issue fixed✅

Previously unaddressed issues to fix:
- When accessing dog preview screen through favourites, dog breed name doesn't appear
- Favourites button isn't operational also

**Comment by filipo203** [comment]
Attempted fix at tackling disappearing dog images and favourites button operation. 

Observations:
-Fix appears to be working but sometimes repeated use of favourites toggle when previewing images from favourites list in UserScreen still causes same issue to occur randomly. Needs testing.

**Comment by charlee-dev** [comment]
ow i only just spotted that you have one ViewModel for all screens which is a no no. It will make the app hold the big object in the memory for the whole app lifecycle. Android my simply kill your app because it uses to much resources (RAM). I know your app is not very big but the rule is to always have separate VM for each screen.

**Comment by filipo203** [comment]
ViewModel Update: 
Split the original viewmodel into 3 separate viewmodels:
- DogViewModel ~ saves dog names. provides dog names for app and search function
- DogPicsViewModel ~ saves dog images, provides dog images for app, toggle favourites function and gets favourite dog images (to display favourite dog accessed from favourites list)
- UserViewModel ~ inserts username, gets username, dialog event and gets favourite dog images (for favourites list)

**Comment by filipo203** [comment]
UPDATE:
- Changed Live Data objects to State Flow. Had to update how data was handled from the ViewModels to the UI.
- Dog preview screen uses both data from list of dogs and list of favourite dogs. When previewing dogs from favourites list, dogs would sometimes disappear if unfavourited.
- Error handling when issue with previewing dog image occurs. User sees an error message and can go back to the previous screen instead of app crashing.

**Pull request merged**
